### PR TITLE
Release with registrator

### PR DESCRIPTION
**Pull request by briochemc**
I am trying to make the little changes needed for the update via the new Registrator bot.

### CODE REVIEW

**Comment by briochemc** [comment]
With these changes you can simply make the release: 
1. a few clicks to install the Registrator bot on GitHub (link is on [Registrator.jl](https://github.com/JuliaRegistries/Registrator.jl)'s ReadMe)
2. a few clicks to Install the TagBot if you want ([link](https://github.com/apps/julia-tagbot)) 
3. comment `@JuliaRegistrator register()` on the PR

**Comment by rafaqz** [comment]
Thanks!

I realised a few days ago that we could specify which types to flatten and ignore in the method call instead of in the overrides as I've done in this version. Which makes this much more powerful - you could eg. flatten just the arrays from a nested struct, and rebuild it with them as a different kind of array, or whatever, without doing method overrides like you have to in this version.

So I don't want to make a release of these changes because they present an API that I'm going to totally remove in a few weeks. 

It also means getting rid of the `flatten(Vector, x)` syntax, its actually less chars to do the `[flatten(x)...]` manually yourself anyway.

**Comment by briochemc** [comment]
I'm not sure I understand all this yet, but I trust whatever you do there! I just wanted to help out :)

**Comment by rafaqz** [comment]
Thanks! :)

To explain better, flatten is mostly about flattening structs to tuples of `Number` right now. But it should be about flattening and reconstructing any types you want to specify.

So you could do `flatten(Symbol, x) = (:all, :symbols, :from, :the, :struct)` or whatever you need, say only numbers in Real or AbstractFloat with `flatten(AbstractFloat, x)`.

I'll have time to finish it in 3 weeks! So I'll push the changes then, and leave the current changes just on master here until then.

**Comment by briochemc** [comment]
Hi there, I thought I'd just revive this post to serve as a reminder, just in case you have finished celebrating your PhD award! 👍

**Comment by rafaqz** [comment]
Just my masters! But yeah Im on it tomorrow.

**Pull request merged**
