### PR TITLE
Fix reconstruct failing on union types

### LINKED ISSUE #32: New reconstruct does not handle union types
Yet another bug in the new, type-stable reconstruct implementation (sorry!).

structs which contain Union-typed fields, e.g:

```julia
struct A{T}
  val::Union{Missing,T}
end
```

cause `reconstruct` to fail because `fieldnames` is not defined on union types.

For now, the simplest solution is probably to just add a check for `isa(T,Union)` and fall back to a runtime type check in such cases (I don't foresee this being a problem in use cases such as `ModelParameters.jl`). And in general, this is the most conservative solution since there is no way to generate type stable code for arbitrary union types. However, it might be possible to handle `Union{Missing,...}` and `Union{Nothing,...}` in a special way that preserves type-stability. I would have to think more about it, though, and I don't see this being a particularly meaningful use-case any time soon.

### PR DESCRIPTION
**Pull request by bgroenks96**
Fixes #32

### CODE REVIEW

**Comment by bgroenks96** [comment]
@rafaqz Are there any other weird corner cases you can think of?

**Comment by rafaqz** [comment]
I'm not sure. At least make sure that https://github.com/rafaqz/ModelParameters.jl/issues/28 works?

**Comment by bgroenks96** [comment]
It does, I checked!

**Comment by bgroenks96** [comment]
And everything is still type stable :+1: ... so mission accomplished, I guess?

**Pull request merged**
